apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: postgresql-persistent
  labels:
    app: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
    name: postgresql
  replicas: 2
  template:
    metadata:
      labels:
        app: postgresql
        name: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:9.6
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: postgresql
        ports:
        - containerPort: 5432
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql

